// Preliminary Biology — Section I multiple-choice questions
// Sourced from Exam Choice 2022, Independent 2022, Girraween 2020/2022/2023,
// North Sydney Girls 2020/2023 trial papers, cross-checked against each
// paper's own official answer key or highlighted-answer solutions copy.
const QUESTIONS = [
  {
    "id": "2022-Q1",
    "year": 2022,
    "n": 1,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "EC22_q01.png",
    "w": 900,
    "h": 412,
    "ans": ["B"],
    "expl": "Brahman cattle and camels are not closely related, yet both independently evolved a fat hump as a heat-loss adaptation to hot, dry conditions — the hallmark of convergent evolution, not shared ancestry."
  },
  {
    "id": "2022-Q2",
    "year": 2022,
    "n": 2,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "EC22_q02.png",
    "w": 900,
    "h": 378,
    "ans": ["B"],
    "expl": "Concentrating urine is an internal bodily process, not a visible physical feature or a behaviour, which makes it a physiological adaptation."
  },
  {
    "id": "2022-Q7",
    "year": 2022,
    "n": 7,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "EC22_q07.png",
    "w": 900,
    "h": 344,
    "ans": ["D"],
    "expl": "Darwin's observations of the Galapagos finches — closely related species with beaks suited to different food sources on different islands — were central evidence for his theory of evolution by natural selection."
  },
  {
    "id": "2022-Q11",
    "year": 2022,
    "n": 11,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "EC22_q11.png",
    "w": 900,
    "h": 682,
    "ans": ["A"],
    "expl": "Fewer amino acid differences means a more recent common ancestor. Chimpanzee (0 differences) is most closely related, then Gorilla (1), then Rhesus monkey (8) is least closely related."
  },
  {
    "id": "2022-Q12",
    "year": 2022,
    "n": 12,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "EC22_q12.png",
    "w": 900,
    "h": 374,
    "ans": ["D"],
    "expl": "Molecular evidence for evolution rests on the assumption that species with more similar DNA or protein sequences share more recent common ancestry — i.e. biochemical similarity reflects genetic similarity."
  },
  {
    "id": "2022-Q13",
    "year": 2022,
    "n": 13,
    "topic": "Organisation of Living Things",
    "subs": ["Organisation of Cells"],
    "img": "EC22_q13.png",
    "w": 900,
    "h": 378,
    "ans": ["C"],
    "expl": "Root hairs greatly increase the surface area of the root's epidermis in contact with soil water, which is their main function — maximising water (and mineral) absorption."
  },
  {
    "id": "2022-Q15",
    "year": 2022,
    "n": 15,
    "topic": "Working Scientifically",
    "subs": ["Questioning and Predicting"],
    "img": "EC22_q15.png",
    "w": 900,
    "h": 694,
    "ans": ["A"],
    "expl": "The independent variable is the one deliberately changed by the investigator — here, air temperature — while volume of water transpired is measured in response (the dependent variable)."
  },
  {
    "id": "2022-Q16",
    "year": 2022,
    "n": 16,
    "topic": "Working Scientifically",
    "subs": ["Planning and Conducting Investigations"],
    "img": "EC22_q16.png",
    "w": 900,
    "h": 626,
    "ans": ["D"],
    "expl": "Air humidity also strongly affects transpiration rate, so it must be held constant across trials — otherwise a change in transpiration couldn't be confidently attributed to temperature alone."
  },
  {
    "id": "2022-Q17",
    "year": 2022,
    "n": 17,
    "topic": "Working Scientifically",
    "subs": ["Processing and Analysing Data"],
    "img": "EC22_q17.png",
    "w": 900,
    "h": 592,
    "ans": ["A"],
    "expl": "Transpiration rate increases steadily as temperature rises, consistent with the hypothesis. A single investigation can support a hypothesis, but in science no single experiment ever proves one absolutely."
  },
  {
    "id": "2022-Q18",
    "year": 2022,
    "n": 18,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "EC22_q18.png",
    "w": 900,
    "h": 756,
    "ans": ["D"],
    "expl": "Drying out (desiccation) is an abiotic factor, so it sets the upper limit; predators and competitors are biotic factors, so they set the lower limit — matching row (D)."
  },
  {
    "id": "2022-IND-Q1",
    "year": 2022,
    "n": 1,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "IND22_q01.png",
    "w": 1604,
    "h": 1253,
    "ans": ["D"],
    "expl": "A species moved by human activity to a location outside its natural range is, by definition, an introduced species — prickly pear is a classic Australian example."
  },
  {
    "id": "2022-IND-Q2",
    "year": 2022,
    "n": 2,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "IND22_q02.png",
    "w": 1554,
    "h": 760,
    "ans": ["C"],
    "expl": "Low light intensity reaching the forest floor beneath a dense canopy is the main reason light-hungry grasses struggle to grow there."
  },
  {
    "id": "2022-IND-Q3",
    "year": 2022,
    "n": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "IND22_q03.png",
    "w": 1614,
    "h": 1984,
    "ans": ["D"],
    "expl": "Lipids yield roughly double the energy per gram of carbohydrates or proteins, since they contain more energy-rich C-H bonds relative to oxygen."
  },
  {
    "id": "2022-IND-Q4",
    "year": 2022,
    "n": 4,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "IND22_q04.png",
    "w": 1612,
    "h": 2056,
    "ans": ["B"],
    "expl": "In a predator-prey relationship the predator population peak lags just behind the prey population peak, with both oscillating out of phase over time."
  },
  {
    "id": "2022-IND-Q5",
    "year": 2022,
    "n": 5,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "IND22_q05.png",
    "w": 1614,
    "h": 1961,
    "ans": ["C"],
    "expl": "The fine surface detail and 3D depth visible on the beetle's exoskeleton is characteristic of a scanning electron microscope image, which images surfaces rather than thin internal sections."
  },
  {
    "id": "2022-IND-Q6",
    "year": 2022,
    "n": 6,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "IND22_q06.png",
    "w": 1612,
    "h": 1232,
    "ans": ["A"],
    "expl": "An organelle that stores DNA and controls the cell's activities is the nucleus."
  },
  {
    "id": "2022-IND-Q7",
    "year": 2022,
    "n": 7,
    "topic": "Organisation of Living Things",
    "subs": ["Organisation of Cells"],
    "img": "IND22_q07.png",
    "w": 1580,
    "h": 788,
    "ans": ["D"],
    "expl": "The correct hierarchy is cells → tissues → organs → systems → organism, so organisms are made up of systems."
  },
  {
    "id": "2022-IND-Q8",
    "year": 2022,
    "n": 8,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "IND22_q08.png",
    "w": 1622,
    "h": 1998,
    "ans": ["A"],
    "expl": "Xylem vessels have thick, lignified walls that make them the more structurally distinct tissue in a stem cross-section."
  },
  {
    "id": "2022-IND-Q9",
    "year": 2022,
    "n": 9,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "IND22_q09.png",
    "w": 1620,
    "h": 2002,
    "ans": ["D"],
    "expl": "Engulfing and internalising a pathogen, as shown here, is phagocytosis — the process macrophages and neutrophils use to remove pathogens from the body."
  },
  {
    "id": "2022-IND-Q10",
    "year": 2022,
    "n": 10,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "IND22_q10.png",
    "w": 1606,
    "h": 1987,
    "ans": ["B"],
    "expl": "Resistance evolves because bacteria that happen to survive an antibiotic are the ones that go on to reproduce, passing their resistance genes to the next generation."
  },
  {
    "id": "2022-IND-Q11",
    "year": 2022,
    "n": 11,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "IND22_q11.png",
    "w": 1604,
    "h": 1293,
    "ans": ["A"],
    "expl": "Different Eucalypt forest types mainly reflect the different selection pressures (rainfall, soil, fire regime) each area imposes, favouring different adaptations."
  },
  {
    "id": "2022-IND-Q12",
    "year": 2022,
    "n": 12,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "IND22_q12.png",
    "w": 1436,
    "h": 684,
    "ans": ["B"],
    "expl": "Blood picks up oxygen and releases carbon dioxide as it passes the alveoli, so oxygen concentration rises while carbon dioxide concentration falls."
  },
  {
    "id": "2022-IND-Q13",
    "year": 2022,
    "n": 13,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "IND22_q13.png",
    "w": 1614,
    "h": 1354,
    "ans": ["A"],
    "expl": "Light-dependent reactions occur in the thylakoid membranes, splitting water to produce ATP, NADPH and O2; light-independent reactions occur in the stroma, using those products to fix carbon into sugars."
  },
  {
    "id": "2022-IND-Q14",
    "year": 2022,
    "n": 14,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "IND22_q14.png",
    "w": 1524,
    "h": 628,
    "ans": ["A"],
    "expl": "To trace where the carbon in the resulting glucose came from, the radioactive label needs to be on the carbon that's supplied — i.e. carbon-14 in the carbon dioxide."
  },
  {
    "id": "2022-IND-Q15",
    "year": 2022,
    "n": 15,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "IND22_q15.png",
    "w": 1426,
    "h": 489,
    "ans": ["C"],
    "expl": "Both species benefit here — the bird gains a food source and the plant gains a pollinator — which makes this mutualism."
  },
  {
    "id": "2022-IND-Q16",
    "year": 2022,
    "n": 16,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "IND22_q16.png",
    "w": 1596,
    "h": 825,
    "ans": ["D"],
    "expl": "The timeline shows the earliest penguin fossils dating to the Neogene period, which spans the Miocene and Pliocene epochs shown on the diagram."
  },
  {
    "id": "2022-IND-Q17",
    "year": 2022,
    "n": 17,
    "topic": "Organisation of Living Things",
    "subs": ["Organisation of Cells"],
    "img": "IND22_q17.png",
    "w": 1595,
    "h": 655,
    "ans": ["C"],
    "expl": "Cell differentiation and specialisation happen because different genes are switched on or off in different cells, not because of any change to the DNA itself."
  },
  {
    "id": "2022-IND-Q18",
    "year": 2022,
    "n": 18,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "IND22_q18.png",
    "w": 1614,
    "h": 950,
    "ans": ["B"],
    "expl": "At high light intensity the curve plateaus at high CO2 concentrations, showing that once another factor becomes limiting, extra CO2 no longer increases the rate of photosynthesis."
  },
  {
    "id": "2022-IND-Q19",
    "year": 2022,
    "n": 19,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "IND22_q19.png",
    "w": 1614,
    "h": 368,
    "ans": ["C"],
    "expl": "Rock paintings depicting different species are direct evidence of which megafauna species existed and were observed — i.e. their variety — rather than their behaviour, diet, or why they went extinct."
  },
  {
    "id": "2022-IND-Q20",
    "year": 2022,
    "n": 20,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "IND22_q20.png",
    "w": 1500,
    "h": 604,
    "ans": ["A"],
    "expl": "Lower oxygen-18 in ice corresponds to warmer periods, and the data here shows this alongside rising carbon dioxide — evidence linking rising CO2 to rising temperature."
  },
  {
    "id": "G22-Q1",
    "year": 2022,
    "n": 1,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "G22_q01.png",
    "w": 1241,
    "h": 395,
    "ans": ["D"],
    "expl": "Nucleic acids, proteins, lipids and vitamin C are all organic (carbon-based) molecules; the others include inorganic substances like iron or phosphorus."
  },
  {
    "id": "G22-Q2",
    "year": 2022,
    "n": 2,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "G22_q02.png",
    "w": 1231,
    "h": 1217,
    "ans": ["A"],
    "expl": "Centrioles are the organelles typically labelled near the nucleus in animal-cell micrographs, involved in cell division."
  },
  {
    "id": "G22-Q3",
    "year": 2022,
    "n": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G22_q03.png",
    "w": 1333,
    "h": 648,
    "ans": ["D"],
    "expl": "Facilitated diffusion moves particles down their concentration gradient through a membrane protein channel — still passive, unlike active transport."
  },
  {
    "id": "G22-Q4",
    "year": 2022,
    "n": 4,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "G22_q04.png",
    "w": 1292,
    "h": 1691,
    "ans": ["B"],
    "expl": "The Grants' finch data is a classic real-world example of natural selection acting on beak depth under drought conditions."
  },
  {
    "id": "G22-Q6",
    "year": 2022,
    "n": 6,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "G22_q06.png",
    "w": 1307,
    "h": 405,
    "ans": ["A"],
    "expl": "Stomata's main role is controlling gas exchange and water loss between the leaf's internal and external environment."
  },
  {
    "id": "G22-Q7",
    "year": 2022,
    "n": 7,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "G22_q07.png",
    "w": 1329,
    "h": 1179,
    "ans": ["B"],
    "expl": "In a vascular bundle cross-section, phloem carries organic nutrients like sucrose around the plant."
  },
  {
    "id": "G22-Q8",
    "year": 2022,
    "n": 8,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "G22_q08.png",
    "w": 1116,
    "h": 809,
    "ans": ["B"],
    "expl": "Similar limb-bone structure across different mammals reflects divergent evolution from a shared ancestor, each adapted to a different use."
  },
  {
    "id": "G22-Q9",
    "year": 2022,
    "n": 9,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "G22_q09.png",
    "w": 1025,
    "h": 856,
    "ans": ["A"],
    "expl": "0.8 µm converts to 0.0008 mm (1 µm = 0.001 mm), a standard unit-conversion skill for interpreting micrographs."
  },
  {
    "id": "G20-Q1",
    "year": 2020,
    "n": 1,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "G20_q01.png",
    "w": 1293,
    "h": 367,
    "ans": ["C"],
    "expl": "A community is defined as different species living and interacting together in a specific area."
  },
  {
    "id": "G20-Q2",
    "year": 2020,
    "n": 2,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G20_q02.png",
    "w": 1035,
    "h": 449,
    "ans": ["B"],
    "expl": "Light-dependent reactions use light energy to split water and produce ATP; producing glucose (fixing CO2) is a light-independent step."
  },
  {
    "id": "G20-Q3",
    "year": 2020,
    "n": 3,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "G20_q03.png",
    "w": 1448,
    "h": 1190,
    "ans": ["A"],
    "expl": "Long-term smoke exposure damages and reduces alveoli surface area, impairing gas exchange — the basis of COPD."
  },
  {
    "id": "G20-Q5",
    "year": 2020,
    "n": 5,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "G20_q05.png",
    "w": 1017,
    "h": 366,
    "ans": ["D"],
    "expl": "The pulmonary artery is the vessel that carries deoxygenated blood from the heart to the lungs."
  },
  {
    "id": "G20-Q6",
    "year": 2020,
    "n": 6,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "G20_q06.png",
    "w": 1292,
    "h": 367,
    "ans": ["B"],
    "expl": "During expiration, contracting the chest cavity raises lung air pressure above atmospheric pressure, pushing air out."
  },
  {
    "id": "G20-Q7",
    "year": 2020,
    "n": 7,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "G20_q07.png",
    "w": 1164,
    "h": 596,
    "ans": ["C"],
    "expl": "Companion cells support sieve tube elements via plasmodesmata connections and provide the mitochondria/nucleus sieve cells lack."
  },
  {
    "id": "G20-Q8",
    "year": 2020,
    "n": 8,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "G20_q08.png",
    "w": 656,
    "h": 321,
    "ans": ["B"],
    "expl": "Energy is transferred between trophic levels through ingestion — one organism eating another."
  },
  {
    "id": "G20-Q10",
    "year": 2020,
    "n": 10,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G20_q10.png",
    "w": 1442,
    "h": 925,
    "ans": ["A"],
    "expl": "Gas bubbles from yeast, sugar and water indicate fermentation — anaerobic cellular respiration producing CO2."
  },
  {
    "id": "G20-Q11",
    "year": 2020,
    "n": 11,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "G20_q11.png",
    "w": 1048,
    "h": 805,
    "ans": ["C"],
    "expl": "A wilting plant shows water loss (transpiration) exceeding water uptake by the roots."
  },
  {
    "id": "G20-Q14",
    "year": 2020,
    "n": 14,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "G20_q14.png",
    "w": 1433,
    "h": 1086,
    "ans": ["D"],
    "expl": "Cane toads are a classic Australian example of an introduced species whose population grew unchecked without natural predators."
  },
  {
    "id": "G20-Q15",
    "year": 2020,
    "n": 15,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "G20_q15.png",
    "w": 1484,
    "h": 2775,
    "ans": ["D"],
    "expl": "Out-of-phase oscillating population curves for two interacting species are the signature pattern of predator-prey dynamics."
  },
  {
    "id": "G23-Q3",
    "year": 2023,
    "n": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G23_q03.png",
    "w": 1394,
    "h": 658,
    "ans": ["B"],
    "expl": "This equation is aerobic respiration (glucose + oxygen); it occurs in both plant and animal cells, producing water and carbon dioxide."
  },
  {
    "id": "G23-Q6",
    "year": 2023,
    "n": 6,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G23_q06.png",
    "w": 1459,
    "h": 373,
    "ans": ["B"],
    "expl": "Water moving into root hair cells from soil is osmosis, a passive process — active transport moves substances against a gradient, using energy."
  },
  {
    "id": "G23-Q7",
    "year": 2023,
    "n": 7,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G23_q07.png",
    "w": 1479,
    "h": 544,
    "ans": ["B"],
    "expl": "The labelled water produces labelled O₂ gas (O¹⁸₂) — showing the oxygen gas released in photosynthesis comes from water, not from glucose. Since that oxygen leaves as gas rather than being incorporated into the sugar, glucose's own oxygen atoms must come from the other reactant, carbon dioxide."
  },
  {
    "id": "G23-Q8",
    "year": 2023,
    "n": 8,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G23_q08.png",
    "w": 1422,
    "h": 862,
    "ans": ["C"],
    "expl": "With equal volume, the cell with the smallest dimensions has the largest surface area to volume ratio and so exchanges materials most efficiently."
  },
  {
    "id": "G23-Q9",
    "year": 2023,
    "n": 9,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "G23_q09.png",
    "w": 1484,
    "h": 1084,
    "ans": ["A"],
    "expl": "Stomata open at night in desert-adapted (CAM) plants to minimise water loss, so Plant Y likely absorbs most CO2 at night."
  },
  {
    "id": "G23-Q10",
    "year": 2023,
    "n": 10,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "G23_q10.png",
    "w": 1469,
    "h": 454,
    "ans": ["A"],
    "expl": "Anaerobic respiration releases far less energy per glucose molecule than aerobic respiration, since glucose is only partially broken down."
  },
  {
    "id": "G23-Q11",
    "year": 2023,
    "n": 11,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "G23_q11.png",
    "w": 1485,
    "h": 417,
    "ans": ["B"],
    "expl": "Diffusion rate increases with a steeper concentration gradient — here, more CO2 in the blood than the lungs drives it across the alveolus."
  },
  {
    "id": "G23-Q17",
    "year": 2023,
    "n": 17,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "G23_q17.png",
    "w": 1496,
    "h": 1198,
    "ans": ["A"],
    "expl": "Tiktaalik's mix of fish and tetrapod features is transitional-fossil evidence supporting fish-to-reptile evolutionary history."
  },
  {
    "id": "NSG20-Q1",
    "year": 2020,
    "n": 1,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "NSG20_q01.png",
    "w": 1394,
    "h": 1296,
    "ans": ["C"],
    "expl": "Using the principle of superposition and the shared volcanic ash marker layer, fossils in deeper strata are older."
  },
  {
    "id": "NSG20-Q2",
    "year": 2020,
    "n": 2,
    "topic": "Organisation of Living Things",
    "subs": ["Organisation of Cells"],
    "img": "NSG20_q02.png",
    "w": 980,
    "h": 303,
    "ans": ["C"],
    "expl": "The size hierarchy from smallest to largest is cell → organ system → organism (organelles are smaller than cells, tissues sit between)."
  },
  {
    "id": "NSG20-Q3",
    "year": 2020,
    "n": 3,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "NSG20_q03.png",
    "w": 1388,
    "h": 983,
    "ans": ["D"],
    "expl": "Population density is total individuals counted across the quadrats divided by total quadrat area sampled."
  },
  {
    "id": "NSG20-Q5",
    "year": 2020,
    "n": 5,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "NSG20_q05.png",
    "w": 1225,
    "h": 988,
    "ans": ["C"],
    "expl": "The organelle shown (with ribosomes on its surface) is the site of protein synthesis and processing."
  },
  {
    "id": "NSG20-Q9",
    "year": 2020,
    "n": 9,
    "topic": "Working Scientifically",
    "subs": ["Planning and Conducting Investigations"],
    "img": "NSG20_q09.png",
    "w": 1429,
    "h": 303,
    "ans": ["A"],
    "expl": "A valid comparison changes only air temperature between the two tubes, keeping every other variable identical."
  },
  {
    "id": "NSG20-Q10",
    "year": 2020,
    "n": 10,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "NSG20_q10.png",
    "w": 1420,
    "h": 1115,
    "ans": ["C"],
    "expl": "Ice core and radiometric data together let scientists cross-reference temperature and ice volume changes over geological time."
  },
  {
    "id": "NSG20-Q11",
    "year": 2020,
    "n": 11,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "NSG20_q11.png",
    "w": 1434,
    "h": 835,
    "ans": ["B"],
    "expl": "Unrelated gliding mammals evolving similar limb membranes independently is convergent evolution — similar environmental pressures, not shared ancestry."
  },
  {
    "id": "NSG20-Q12",
    "year": 2020,
    "n": 12,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "NSG20_q12.png",
    "w": 1426,
    "h": 434,
    "ans": ["C"],
    "expl": "Both the fungus (sugars) and plant (nutrients, drought tolerance) benefit — this is mutualism."
  },
  {
    "id": "NSG20-Q13",
    "year": 2020,
    "n": 13,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "NSG20_q13.png",
    "w": 1397,
    "h": 390,
    "ans": ["C"],
    "expl": "At 12.5% remaining carbon-14, three half-lives have passed (100%→50%→25%→12.5%): 3 × 5730 ≈ 17,190 years."
  },
  {
    "id": "NSG20-Q14",
    "year": 2020,
    "n": 14,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "NSG20_q14.png",
    "w": 1305,
    "h": 905,
    "ans": ["A"],
    "expl": "A large caecum houses microbes that break down the tough cellulose in a koala's eucalyptus diet."
  },
  {
    "id": "NSG20-Q15",
    "year": 2020,
    "n": 15,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "NSG20_q15.png",
    "w": 1020,
    "h": 303,
    "ans": ["C"],
    "expl": "Hunting pressure from arriving humans combined with a drying climate is the leading explanation for Australian megafauna extinction."
  },
  {
    "id": "NSG20-Q16",
    "year": 2020,
    "n": 16,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "NSG20_q16.png",
    "w": 781,
    "h": 304,
    "ans": ["B"],
    "expl": "Tree hollows, grass and microbial disease are all living components of the environment — biotic factors."
  },
  {
    "id": "NSG20-Q17",
    "year": 2020,
    "n": 17,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "NSG20_q17.png",
    "w": 1081,
    "h": 716,
    "ans": ["A"],
    "expl": "Similar early structures across unrelated vertebrate embryos reflect divergent evolution from a shared ancestor."
  },
  {
    "id": "NSG20-Q18",
    "year": 2020,
    "n": 18,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "NSG20_q18.png",
    "w": 1046,
    "h": 304,
    "ans": ["B"],
    "expl": "Removing topsoil is what damages a site; rehabilitation instead involves stockpiling and later replacing topsoil."
  },
  {
    "id": "NSG20-Q19",
    "year": 2020,
    "n": 19,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "NSG20_q19.png",
    "w": 1424,
    "h": 986,
    "ans": ["A"],
    "expl": "Eucalypt leaves show structural adaptations (shape, orientation, waxy cuticle) that reduce water loss in hot, dry conditions."
  },
  {
    "id": "NSG20-Q20",
    "year": 2020,
    "n": 20,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "NSG20_q20.png",
    "w": 1256,
    "h": 941,
    "ans": ["D"],
    "expl": "Only veins need valves, since their low blood pressure requires help preventing backflow — arteries don't have them."
  },
  {
    "id": "NSG23-Q1",
    "year": 2023,
    "n": 1,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "NSG23_q01.png",
    "w": 1326,
    "h": 1159,
    "ans": ["D"],
    "expl": "The cleaner wrasse normally helps the host (mutualism); occasionally biting off living tissue for food shifts that interaction toward parasitism."
  },
  {
    "id": "NSG23-Q2",
    "year": 2023,
    "n": 2,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "NSG23_q02.png",
    "w": 1242,
    "h": 364,
    "ans": ["B"],
    "expl": "Food travels oesophagus → stomach → small intestine → large intestine → rectum through the human digestive system."
  },
  {
    "id": "NSG23-Q3",
    "year": 2023,
    "n": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "NSG23_q03.png",
    "w": 1332,
    "h": 1183,
    "ans": ["B"],
    "expl": "In the phospholipid bilayer, hydrophilic phosphate heads face outward (towards water) while hydrophobic lipid tails point inward."
  },
  {
    "id": "NSG23-Q4",
    "year": 2023,
    "n": 4,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "NSG23_q04.png",
    "w": 1332,
    "h": 480,
    "ans": ["C"],
    "expl": "Excreting salt through leaf glands is an internal bodily process — a physiological adaptation, not a visible structural feature."
  },
  {
    "id": "NSG23-Q6",
    "year": 2023,
    "n": 6,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "NSG23_q06.png",
    "w": 1331,
    "h": 588,
    "ans": ["C"],
    "expl": "A cell with a chloroplast (autotroph) and a nucleus (eukaryote) is an autotrophic eukaryote."
  },
  {
    "id": "NSG23-Q7",
    "year": 2023,
    "n": 7,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "NSG23_q07.png",
    "w": 1132,
    "h": 1004,
    "ans": ["D"],
    "expl": "A graph showing enzyme activity rising then plateauing as a variable increases is characteristic of increasing substrate concentration."
  },
  {
    "id": "NSG23-Q8",
    "year": 2023,
    "n": 8,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "NSG23_q08.png",
    "w": 1333,
    "h": 419,
    "ans": ["A"],
    "expl": "Vertical, pale leaves and fewer stomata are structural adaptations that reduce water loss (transpiration) in hot, dry climates."
  },
  {
    "id": "NSG23-Q9",
    "year": 2023,
    "n": 9,
    "topic": "Ecosystem Dynamics",
    "subs": ["Population Dynamics"],
    "img": "NSG23_q09.png",
    "w": 1333,
    "h": 1802,
    "ans": ["A"],
    "expl": "Both populations rise and fall together in phase (not one lagging the other) — the pattern expected when two species compete for a shared, fluctuating resource, unlike predator-prey cycles which run out of phase."
  },
  {
    "id": "NSG23-Q10",
    "year": 2023,
    "n": 10,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "NSG23_q10.png",
    "w": 1332,
    "h": 1279,
    "ans": ["A"],
    "expl": "Sharks and dolphins independently evolved similar streamlined body shapes because both face the same selection pressures of moving through water."
  },
  {
    "id": "NSG23-Q11",
    "year": 2023,
    "n": 11,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "NSG23_q11.png",
    "w": 1170,
    "h": 304,
    "ans": ["B"],
    "expl": "Chewing breaks food into smaller pieces, increasing surface area available for digestive enzymes to act on."
  },
  {
    "id": "NSG23-Q12",
    "year": 2023,
    "n": 12,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "NSG23_q12.png",
    "w": 1384,
    "h": 2426,
    "ans": ["D"],
    "expl": "Comparing plants near vs far from the mine tests whether copper tolerance has a genetic basis shaped by selection pressure."
  },
  {
    "id": "NSG23-Q14",
    "year": 2023,
    "n": 14,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "NSG23_q14.png",
    "w": 1332,
    "h": 608,
    "ans": ["A"],
    "expl": "Cane toads are toxic to predators like monitor lizards, causing sharp declines in lizard populations that prey on them."
  },
  {
    "id": "NSG23-Q15",
    "year": 2023,
    "n": 15,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "NSG23_q15.png",
    "w": 1386,
    "h": 2011,
    "ans": ["A"],
    "expl": "The shared bone pattern (humerus, radius, ulna, carpals) across very different vertebrates is homology, evidence of a common ancestor."
  },
];
