// Preliminary Biology — Section II short-answer sub-questions
// Sourced from Exam Choice 2022, Presbyterian 2018, Ravenswood 2021,
// Sydney Girls 2020 and Sydney Tech 2020, with official marking criteria
// and sample answers. Diagram-only sub-parts were dropped or (where the
// underlying data was recoverable) rebuilt as a table.
const SA_QUESTIONS = [
  {
    "id": "2022-Q21(a)",
    "year": 2022,
    "n": 21,
    "part": "a",
    "marks": 3,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "EC22_q21_a.png",
    "w": 900,
    "h": 486,
    "criteria": "Both answers correctly calculated — 3\nOne answer correct with appropriate working — 2\nOne answer correct, no working OR some appropriate working — 1",
    "sample": "Species 1: 2 + 1 + 3 + 2 = 8. 8 ÷ 4 = 2 plants/m².\nSpecies 2: 0 + 3 + 0 + 2 = 5. 5 ÷ 4 = 1.25 plants/m²."
  },
  {
    "id": "2022-Q21(b)",
    "year": 2022,
    "n": 21,
    "part": "b",
    "marks": 1,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "EC22_q21_b.png",
    "w": 900,
    "h": 252,
    "criteria": "Justification related to bias or validity — 1",
    "sample": "Randomly placed quadrats avoid experimental bias. The method is only valid if quadrats are truly representative of the whole area, and random selection makes this more likely."
  },
  {
    "id": "2022-Q21(c)",
    "year": 2022,
    "n": 21,
    "part": "c",
    "marks": 2,
    "topic": "Biological Diversity",
    "subs": ["Effects of the Environment on Organisms"],
    "img": "EC22_q21_c.png",
    "w": 900,
    "h": 354,
    "criteria": "Recognition that Species 2 has an uneven distribution — 1\nExplanation of how this compromises validity — 1",
    "sample": "For this method to be valid, the abundance of organisms within the quadrats must be representative of the whole area. When a species has an uneven distribution, as Species 2 does here, the chance positioning of quadrats will give a wide range of different answers."
  },
  {
    "id": "2022-Q21(d.i)",
    "year": 2022,
    "n": 21,
    "part": "d.i",
    "marks": 1,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "EC22_q21_di.png",
    "w": 900,
    "h": 184,
    "criteria": "Plant named — 1",
    "sample": "Prickly pear."
  },
  {
    "id": "2022-Q21(d.ii)",
    "year": 2022,
    "n": 21,
    "part": "d.ii",
    "marks": 3,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "EC22_q21_dii.png",
    "w": 900,
    "h": 218,
    "criteria": "Discussion incorporating 3 points from: abiotic factors (favourable soil, water availability, etc.), biotic factors (few predators, able to outcompete natives), adaptations (fast reproductive rate, drought tolerance, etc.) — 3\n1–2 of the above — 1–2",
    "sample": "Prickly pear was very successful because it had adaptations well suited to the Australian environment: it is highly drought tolerant and able to outcompete native species for space. It reproduces quickly — birds spread its seeds and it can also reproduce vegetatively, letting it rapidly colonise new areas. It also faced few natural predators in Australia to keep its numbers in check. Together, these factors let it rapidly colonise large areas."
  },
  {
    "id": "2022-Q22(b)",
    "year": 2022,
    "n": 22,
    "part": "b",
    "marks": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "EC22_q22_b.png",
    "w": 900,
    "h": 320,
    "criteria": "Linkage of cell requirements to volume — 1\nLinkage of ability to exchange materials to surface area — 1\nRecognition that X has the larger surface area to volume ratio — 1",
    "sample": "A cell's requirements for oxygen and nutrients are proportional to its volume, while the rate at which it can exchange materials with its environment is proportional to its surface area. As cells get larger, volume increases at a greater rate than surface area, so cell Y has a smaller surface area to volume ratio than cell X and is therefore less able to satisfy its own requirements by exchange across its membrane."
  },
  {
    "id": "2022-Q23(b)",
    "year": 2022,
    "n": 23,
    "part": "b",
    "marks": 4,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "EC22_q23_b.png",
    "w": 900,
    "h": 286,
    "criteria": "Explanation incorporating any 4 of: loading at the source by active transport; identification of phloem as the transport tissue; movement of water from xylem to phloem by osmosis; pressure moving sugars along the phloem (translocation); downloading at the sink — 4\n1–3 of the above — 1–3",
    "sample": "Sugars are made by photosynthesis mainly in the mesophyll cells of the leaf; sucrose is the sugar principally transported in the phloem. Sugars move by active transport from the mesophyll cells into the sieve elements of the phloem, against a concentration gradient. Water is then pulled in from the xylem by osmosis, and the resulting pressure pushes the sugars along the phloem — a process called translocation. Once the sugars reach their destination, they are moved by active transport into the respiring or storage cells that need them."
  },
  {
    "id": "2022-Q24",
    "year": 2022,
    "n": 24,
    "part": "",
    "marks": 6,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "EC22_q24_full.png",
    "w": 900,
    "h": 286,
    "criteria": "Answer incorporating: named species; human-induced selection pressure identified; role in extinction described; biodiversity defined (or implied); lesson learnt; role in predicting future impacts outlined — 6\n1–5 of the above — 1–5",
    "sample": "The Paradise Parrot was once reasonably abundant in inland Queensland and NSW; there have been no reliable sightings for nearly 100 years. Among the human-induced selection pressures likely responsible for its extinction was the introduction of cattle grazing to its home range — overgrazing, replacement of native grasses with agricultural species, and a more severe fire regime are thought to be major contributors, since paradise parrots fed on grass seed. Biodiversity is an expression of the variety of species, the genetic variety within species, and the variety of ecosystems. The lesson from this example is that human activities not directed at a species can still have dire consequences for it — this lets us predict that further land clearing and grazing will lead to the extinction of more species, and shows the importance of retaining and protecting natural areas."
  },
  {
    "id": "2022-Q25(a)",
    "year": 2022,
    "n": 25,
    "part": "a",
    "marks": 3,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "EC22_q25_a.png",
    "w": 900,
    "h": 320,
    "criteria": "Explanation incorporating: variation in the population — some individuals better able to tolerate copper than others; differential survival; favourable trait inherited by offspring; favourable trait becomes more widespread in the population — 3\n2–3 of the above — 1–2",
    "sample": "Within a natural population of A. stolonifera there would be genetic variation — some individuals better able to tolerate copper than others. Once an area becomes contaminated with copper, the more copper-tolerant individuals survive and reproduce more successfully than others. They pass the genes for this tolerance on to their offspring, and these genes become much more frequent in subsequent generations."
  },
  {
    "id": "2022-Q25(b)",
    "year": 2022,
    "n": 25,
    "part": "b",
    "marks": 1,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "EC22_q25_b.png",
    "w": 900,
    "h": 184,
    "criteria": "Selection pressure identified — 1",
    "sample": "Copper (soil contamination / toxicity)."
  },
  {
    "id": "2022-Q26(b)",
    "year": 2022,
    "n": 26,
    "part": "b",
    "marks": 1,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "EC22_q26_b.png",
    "w": 900,
    "h": 560,
    "criteria": "Correct answer — 1",
    "sample": "10% — this is the beaker concentration at which the sausage's mass didn't change, meaning water moved in and out at equal rates, so the solutions were isotonic."
  },
  {
    "id": "2022-Q26(c)",
    "year": 2022,
    "n": 26,
    "part": "c",
    "marks": 3,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "EC22_q26_c.png",
    "w": 900,
    "h": 286,
    "criteria": "Description including 3 of: definition of osmosis (or implied); movement of water from soil into epidermal root cells; movement of water cell-to-cell along an osmotic gradient towards the xylem; movement of water into the xylem; movement of water out of the xylem into leaf cells; movement of water cell-to-cell within the leaf along an osmotic gradient — 3\n1–2 of the above — 1–2",
    "sample": "Osmosis is the movement of water through a selectively permeable membrane from a region of low solute concentration to one of high solute concentration; it is a passive process. The initial movement of water into root epidermal cells is by osmosis, and it moves from cell to cell towards the xylem along an osmotic gradient. Once drawn up the xylem, water moves into leaf cells, again following an osmotic gradient from cell to cell."
  },
  {
    "id": "2022-Q27",
    "year": 2022,
    "n": 27,
    "part": "",
    "marks": 4,
    "topic": "Organisation of Living Things",
    "subs": ["Organisation of Cells"],
    "img": "EC22_q27_full.png",
    "w": 900,
    "h": 184,
    "criteria": "At least one similarity described and two key differences contrasted — 4\nAt least one similarity described and two different features described (not contrasted) — 3\n1–2 of the above — 1–2",
    "sample": "Both colonial organisms and multicellular organisms are collections of cells that interact to some extent, with some interdependence even in colonial organisms. However, while cells in multicellular organisms are differentiated and perform very different functions, there is very little specialisation among the cells of a colonial organism. Cells in multicellular organisms are further grouped into tissues, organs and organ systems, all highly dependent on each other, whereas cells in colonial organisms are not grouped this way and can often survive without the rest of the colony."
  },
  {
    "id": "2022-Q28(a)",
    "year": 2022,
    "n": 28,
    "part": "a",
    "marks": 1,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "EC22_q28_a.png",
    "w": 900,
    "h": 286,
    "criteria": "Correctly identified and justified — 1",
    "sample": "Eukaryote. It has a membrane-bound nucleus — prokaryotes don't have a distinct, membrane-bound nucleus."
  },
  {
    "id": "2022-Q28(c)",
    "year": 2022,
    "n": 28,
    "part": "c",
    "marks": 4,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "EC22_q28_c.png",
    "w": 900,
    "h": 184,
    "criteria": "At least one similarity described and two key differences contrasted — 4\nAt least one similarity described and two different features described (not contrasted) — 3\n1–2 of the above — 1–2",
    "sample": "Both devices provide magnified images of a specimen, but the electron microscope can achieve much greater magnification and resolution than the compound light microscope, since it uses a beam of electrons rather than light waves. This makes it a better tool for observing very small structures such as viruses or the internal structure of membranes. However, specimens for the electron microscope must be dead and undergo special preparation, which is not necessarily true for the compound light microscope — making the compound microscope a better tool for observing larger or living specimens."
  },
  {
    "id": "2022-Q29(b)",
    "year": 2022,
    "n": 29,
    "part": "b",
    "marks": 3,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "EC22_q29_b.png",
    "w": 900,
    "h": 286,
    "criteria": "Explanation in terms of 3 of: decay of radioactive isotopes; C-14 identified as the isotope used in this example; half-lives; regular decay pattern allowing calculation of age — 3\n1–2 of the above — 1–2",
    "sample": "Preserved organic material, such as pollen, contains carbon, which has two main isotopes: C-12 and C-14. These occur in a fixed ratio in living things. C-14 is radioactive and decays to nitrogen-14 at a consistent rate — half of a given sample of C-14 decays every 5,730 years (its half-life). Analysing fossil pollen for its ratio of C-12 to C-14, and comparing this to the ratio in living things, allows a fairly accurate estimate of the fossil's age."
  },
  {
    "id": "2022-Q29(c)",
    "year": 2022,
    "n": 29,
    "part": "c",
    "marks": 3,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "EC22_q29_c.png",
    "w": 900,
    "h": 184,
    "criteria": "Technologies described — 1\nAtmospheric change described — 1\nAssessment made of the importance of the technology — 1",
    "sample": "Ice core drilling and gas analysis are used together to sample the gas composition of the atmosphere throughout history. A core of ice is drilled out, containing air bubbles sealed within it — the deeper the bubbles, the older the trapped air. Analysing these gases reveals changes over time; for example, CO2 levels can be shown to have nearly doubled since pre-industrial times. This technology is critically important as a source of historical atmospheric data, since regular direct atmospheric sampling only began in the 1950s."
  },
  {
    "id": "Presbyterian2018-Q16",
    "year": 2018,
    "n": 16,
    "part": "",
    "marks": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Structure"],
    "img": "Presbyterian2018_16full.png",
    "w": 900,
    "h": 354,
    "criteria": "Names a technology, describes how it is used to determine cell structure, and gives at least one advantage of using it — 3\n1–2 of the above — 1–2",
    "sample": "The electron microscope has improved our understanding of cell structure. Using a beam of fast-moving electrons rather than light, electromagnets bend the beam similarly to how glass lenses bend light in a light microscope, forming an image on a screen or micrograph. This produces a much higher-resolution image with greater depth of field than a light microscope, letting much smaller structures be resolved."
  },
  {
    "id": "Presbyterian2018-Q18(b)",
    "year": 2018,
    "n": 18,
    "part": "b",
    "marks": 4,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "Presbyterian2018_18b.png",
    "w": 900,
    "h": 218,
    "criteria": "Experiment clearly models enzyme action with a clear IV and DV, names the enzyme and substrate, includes a control, and identifies controlled variables — 4\nPart of the above — 1–3",
    "sample": "Using catalase from potato/zucchini and hydrogen peroxide as the substrate, equal volumes of hydrogen peroxide and detergent were placed in identical test tubes, each held at a different water bath temperature (the independent variable). Equal-sized cylinders of potato were added, and after two minutes the height of bubbles produced (the dependent variable) was measured with a ruler. A control used the same set-up without any potato added."
  },
  {
    "id": "Presbyterian2018-Q19",
    "year": 2018,
    "n": 19,
    "part": "",
    "marks": 3,
    "topic": "Organisation of Living Things",
    "subs": ["Organisation of Cells"],
    "img": "Presbyterian2018_19full.png",
    "w": 900,
    "h": 184,
    "criteria": "Names a specific cell/tissue and explains in detail how its structure and/or function relates to its specialisation — 3\nPartial explanation — 1–2",
    "sample": "Capillaries are specialised blood vessels with a diameter of only 5–10 µm, formed from a single layer of epithelial cells just one cell thick. This structure allows nutrients, oxygen, carbon dioxide and wastes to move easily between blood and extracellular fluid. The huge total surface area created by the extensive network of capillaries (around 1000 m²) further supports their function of exchanging materials throughout the body."
  },
  {
    "id": "Presbyterian2018-Q24",
    "year": 2018,
    "n": 24,
    "part": "",
    "marks": 4,
    "topic": "Organisation of Living Things",
    "subs": ["Nutrient and Gas Requirements"],
    "img": "Presbyterian2018_24full.png",
    "w": 900,
    "h": 350,
    "criteria": "Correctly identifies a location and what happens there for both physical and chemical digestion — 4\nPartial — 1–3",
    "sample": "Physical digestion occurs in the mouth, where chewing breaks food into smaller particles, increasing surface area. Chemical digestion occurs in the stomach, where enzymes such as pepsin break proteins down into shorter polypeptide chains."
  },
  {
    "id": "Presbyterian2018-Q25",
    "year": 2018,
    "n": 25,
    "part": "",
    "marks": 3,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "Presbyterian2018_25full.png",
    "w": 900,
    "h": 184,
    "criteria": "Defines convergent evolution and describes one example in detail — 3\nDefines convergent evolution and outlines an example — 2",
    "sample": "Sharks, dolphins, and the fossil record of ichthyosaurs display similar streamlined features despite coming from entirely different animal groups. Convergent evolution occurs because unrelated species living in similar environments — here, an aquatic one — face comparable selection pressures that favour similar features, so each independently evolves those characteristics."
  },
  {
    "id": "Presbyterian2018-Q26",
    "year": 2018,
    "n": 26,
    "part": "",
    "marks": 3,
    "topic": "Working Scientifically",
    "subs": ["Processing and Analysing Data"],
    "img": "Presbyterian2018_26full.png",
    "w": 900,
    "h": 286,
    "criteria": "Explains why sources were reliable (current, expert, unbiased, reputable, consistent with other sources) AND valid (relevant to the question, supported by evidence) — 3",
    "sample": "The sources were valid because they related directly to the question and were supported by evidence, such as references to first-hand experimental and fossil data. They were reliable because they came from trustworthy, reputable publications, were written by experts in evolution and natural selection, were current, unbiased, and consistent with other trustworthy sources."
  },
  {
    "id": "Presbyterian2018-Q27",
    "year": 2018,
    "n": 27,
    "part": "",
    "marks": 2,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "Presbyterian2018_27full.png",
    "w": 900,
    "h": 184,
    "criteria": "Correctly distinguishes punctuated equilibrium from gradualism — 2\nPartial distinction — 1",
    "sample": "Punctuated equilibrium involves isolated episodes of rapid speciation separated by long periods of little or no change, whereas gradualism (the classic view of natural selection) involves small, continuous changes accumulating each generation, gradually leading to a new species."
  },
  {
    "id": "Presbyterian2018-Q28",
    "year": 2018,
    "n": 28,
    "part": "",
    "marks": 5,
    "topic": "Ecosystem Dynamics",
    "subs": ["Future Ecosystems"],
    "img": "Presbyterian2018_28full.png",
    "w": 900,
    "h": 218,
    "criteria": "Names a specific human activity, identifies how it impacted an ecosystem, identifies the restoration practice used, and explains how that practice restored the ecosystem — 5\nPartial coverage of the above — 1–4",
    "sample": "Mining causes considerable ecosystem damage — erosion, biodiversity loss, and soil/water contamination. Australian law requires mining companies to rehabilitate sites after closure. Rehabilitation typically involves removing contaminants, reconstructing and stabilising landforms to control erosion, regenerating the soil to support plant growth, and then revegetating so a self-sustaining ecosystem can re-establish, eventually allowing fauna to return. The Wattle Dam mine near Kambalda, WA, is one example where this process successfully restored the site."
  },
  {
    "id": "Ravenswood2021-Q24",
    "year": 2021,
    "n": 24,
    "part": "",
    "marks": 4,
    "topic": "Organisation of Living Things",
    "subs": ["Transport"],
    "img": "Ravenswood2021_24full.png",
    "w": 900,
    "h": 388,
    "criteria": "Describes the pathway in detail: carbon-14 enters as CO2, is converted to glucose via photosynthesis, converted to sucrose for transport, and stored as starch or used in other organic processes — 4\nPartial pathway (fewer points) — 1–3",
    "sample": "Carbon-14, in the form of CO2, enters the leaf through the stomata and is used as a reactant in photosynthesis to produce glucose, which now contains the carbon-14. This glucose is converted into sucrose and transported around the plant via the phloem, moving from a source to a sink. Once it reaches cells that require it, it is either used in aerobic respiration for energy, used in other organic processes, or stored as starch in the vacuole."
  },
  {
    "id": "Ravenswood2021-Q25",
    "year": 2021,
    "n": 25,
    "part": "",
    "marks": 4,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "Ravenswood2021_25full.png",
    "w": 900,
    "h": 456,
    "criteria": "Correctly matches two adaptations to their type and explains how each overcomes a named selection pressure — 4\nCompletes with errors — 1–3",
    "sample": "Structural — sandy fur colour: camouflages the kangaroo rat from predators, addressing the selection pressure of predation.\nPhysiological — produces highly concentrated urine: this conserves water, addressing the selection pressure of extreme water scarcity in an arid environment."
  },
  {
    "id": "Ravenswood2021-Q26",
    "year": 2021,
    "n": 26,
    "part": "",
    "marks": 4,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "Ravenswood2021_26full.png",
    "w": 900,
    "h": 320,
    "criteria": "Identifies convergent evolution, describes how dolphins and sharks differ, and identifies the similar selection pressures/adaptations that produced their similar features — 3–4\nPartial coverage — 1–2",
    "sample": "This is an example of convergent evolution. Sharks are fish — they have gills and are exothermic — while dolphins are mammals with lungs that are endothermic, so they are not closely related. However, both are hunters exposed to similar selection pressures from living and moving through water: both evolved forward-facing eyes for hunting and a sleek, streamlined, bilateral body shape with fins for efficient directional movement, despite arriving at these features independently."
  },
  {
    "id": "Ravenswood2021-Q27",
    "year": 2021,
    "n": 27,
    "part": "",
    "marks": 8,
    "topic": "Biological Diversity",
    "subs": ["Adaptations"],
    "img": "Ravenswood2021_27full.png",
    "w": 900,
    "h": 422,
    "criteria": "Describes autotroph nutritional requirements, explains how active transport changes osmotic pressure to move water (closing the trap), describes the function of digestive enzymes, and explains the process of evolution by natural selection using this example, using expert terminology throughout — 7–8\nCovers most of the above in general terms — 5–6\nCovers about half of the above — 3–4\nCovers 2–3 of the above — 1–2",
    "sample": "Venus fly traps are autotrophs, gaining most of their energy through photosynthesis, but still need soil nutrients like nitrogen and phosphorus, which are scarce in their native soils — so they supplement this by trapping and digesting insects. To close the trap, the plant uses active transport to pump solutes into the outer trap cells against their concentration gradient, using ATP; this raises solute concentration and draws water in by osmosis, causing the cells to swell and the trap to snap shut. Enzyme-secreting cells then break the trapped insect down into absorbable nutrients. Over many generations, natural selection favoured individuals better able to lure and trap insects: these plants gained more nutrients, were healthier, and more likely to survive and reproduce, passing this trait on until it became widespread in the population."
  },
  {
    "id": "SydneyGirls2020-Q11",
    "year": 2020,
    "n": 11,
    "part": "",
    "marks": 3,
    "topic": "Biological Diversity",
    "subs": ["Theory of Evolution by Natural Selection"],
    "img": "SydneyGirls2020_11full.png",
    "w": 900,
    "h": 456,
    "criteria": "Relates two similarities/differences in adaptations to the theory of evolution by natural selection, referencing plausible evolutionary processes with specific examples — 3\nRelates one similarity/difference to one evolutionary process — 2\nCites one similarity/difference, or describes the theory generally — 1",
    "sample": "Both species adapted the ability to tear meat — L. scagliai with a sharp beak, the Velociraptor with sharp teeth. After non-avian dinosaurs went extinct, L. scagliai's ancestors evolved this trait through convergent evolution, filling an ecological niche left empty by the extinction, favouring survival and reproduction. In contrast, L. scagliai has a feathered coat while the Velociraptor has scales: before the extinction, avian dinosaur ancestors developed feathers through divergent evolution as they filled a new niche, a trait L. scagliai retains despite most likely being flightless."
  },
  {
    "id": "SydneyGirls2020-Q12",
    "year": 2020,
    "n": 12,
    "part": "",
    "marks": 4,
    "topic": "Ecosystem Dynamics",
    "subs": ["Past Ecosystems"],
    "img": "SydneyGirls2020_12full.png",
    "w": 900,
    "h": 482,
    "criteria": "Explains how the research challenges the previous assumption, referencing specific data from the table — 2\nLinks data to the challenge, or cites one relevant piece of information — 1",
    "sample": "It was previously thought Thylacines went extinct on mainland Australia 2,000–3,000 years ago. However, this painting is classified as Art Phase 3, dated to approximately 1,600–300 years before present — significantly more recent than the assumed extinction date. This suggests Thylacines may have survived on the mainland much more recently than previously believed, challenging the earlier assumption."
  },
  {
    "id": "SydneyTech2020-Q28",
    "year": 2020,
    "n": 28,
    "part": "",
    "marks": 3,
    "topic": "Cells as the Basis of Life",
    "subs": ["Cell Function"],
    "img": "SydneyTech2020_28full.png",
    "w": 900,
    "h": 354,
    "criteria": "Correctly identifies endocytosis and explains why, referencing the direction of membrane movement shown in the diagram — 3\nPartial explanation — 1–2",
    "sample": "Pinocytosis is a form of endocytosis. As shown in the diagram, the plasma membrane folds inward around extracellular fluid and dissolved substances, engulfing them and pinching off to form a vesicle that moves material into the cell. Since material is moving into the cell rather than being released from it, this is endocytosis, not exocytosis."
  },
];
